# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - refs/heads/dfp-data
variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerBuild
    displayName: "Docker Build Job"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@1
      displayName: Build an image
      continueOnError: true
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'DevOps_RGDEVDVLGENDFPWE01_contributor'
        azureContainerRegistry: 'acrdevdvlstr01.azurecr.io'
        command: 'Build an image'
        dockerFile: 'src/app/SGRE.TSA/Dockerfile'
        imageName: 'acrdevdvlstr01.azurecr.io/tsa-data:$(Build.BuildId)'

    - task: Docker@1
      displayName: Push an image
      continueOnError: true
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'DevOps_RGDEVDVLGENDFPWE01_contributor'
        azureContainerRegistry: 'acrdevdvlstr01.azurecr.io'
        command: 'Push an image'
        imageName: 'acrdevdvlstr01.azurecr.io/tsa-data:$(Build.BuildId)'
