// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGRE.TSA.DataStore.API;

namespace SGRE.TSA.DataStore.API.Migrations
{
    [DbContext(typeof(TsaContext))]
    [Migration("20201214122253_changesOnModelClass")]
    partial class changesOnModelClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CertificationName")
                        .HasColumnType("text")
                        .HasColumnName("certification_name");

                    b.HasKey("Id")
                        .HasName("pk_certifications");

                    b.ToTable("certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificationName = "Tower component certificate"
                        },
                        new
                        {
                            Id = 2,
                            CertificationName = "Site Suitability Design Assessment (SSDA)"
                        },
                        new
                        {
                            Id = 3,
                            CertificationName = "Tower component certificate & Site Suitability Design Assessment (SSDA)"
                        },
                        new
                        {
                            Id = 4,
                            CertificationName = "none"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country_name");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_countries_region_id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "China",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Japan",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "South Korea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Australia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "Vietnam",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "New Zealand",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Philippines",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Indonesia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Taiwan",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Pakistan",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Mongolia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Thailand",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Myanmar",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "New Caledonia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Cambodia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Laos",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Brazil",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "India",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Sri Lanka",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Bangladesh",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Brazil",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Mexico",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Peru",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Dominican Rep.",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "Argentina",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Panama",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Chile",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Uruguay",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Colombia",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 30,
                            CountryName = "Belize",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 31,
                            CountryName = "Nicaragua",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 32,
                            CountryName = "Jamaica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 33,
                            CountryName = "Guatemala",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 34,
                            CountryName = "Honduras",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 35,
                            CountryName = "Costa Rica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 36,
                            CountryName = "El Salvador",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 37,
                            CountryName = "Cuba",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 38,
                            CountryName = "Dominica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 39,
                            CountryName = "Guyana",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 40,
                            CountryName = "Ecuador",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 41,
                            CountryName = "Guadeloupe",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 42,
                            CountryName = "Puerto Rico",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 43,
                            CountryName = "Trinidad Tobago",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 44,
                            CountryName = "Bahamas",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 45,
                            CountryName = "Bolivia",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 46,
                            CountryName = "Barbados",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 47,
                            CountryName = "Ireland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 48,
                            CountryName = "Sweden",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 49,
                            CountryName = "Germany",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 50,
                            CountryName = "Romania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 51,
                            CountryName = "Croatia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 52,
                            CountryName = "Finland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 53,
                            CountryName = "Belgium",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 54,
                            CountryName = "Uzbekistan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 55,
                            CountryName = "Serbia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 56,
                            CountryName = "United Kingdom",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 57,
                            CountryName = "Poland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 58,
                            CountryName = "Saudi Arabia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 59,
                            CountryName = "Denmark",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 60,
                            CountryName = "Utd Arab Emir.",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 61,
                            CountryName = "Ukraine",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 62,
                            CountryName = "Bulgaria",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 63,
                            CountryName = "Azerbaijan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 64,
                            CountryName = "Turkey",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 65,
                            CountryName = "Norway",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 66,
                            CountryName = "Moldovia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 67,
                            CountryName = "Iran Islamic Republic of",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 68,
                            CountryName = "Russian Fed.",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 69,
                            CountryName = "Bosnia-Herz.",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 70,
                            CountryName = "Israel",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 71,
                            CountryName = "Lebanon",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 72,
                            CountryName = "Kazakhstan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 73,
                            CountryName = "Slovenia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 74,
                            CountryName = "Netherlands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 75,
                            CountryName = "Hungary",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 76,
                            CountryName = "Albania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 77,
                            CountryName = "Austria",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 78,
                            CountryName = "Oman",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 79,
                            CountryName = "Switzerland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 80,
                            CountryName = "Georgia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 81,
                            CountryName = "Syrian Arab Republic",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 82,
                            CountryName = "Macedonia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 83,
                            CountryName = "Luxembourg",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 84,
                            CountryName = "Kuwait",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 85,
                            CountryName = "Czech Republic",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 86,
                            CountryName = "Yemen",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 87,
                            CountryName = "Belarus",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 88,
                            CountryName = "Lithuania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 89,
                            CountryName = "Iceland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 90,
                            CountryName = "Estonia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 91,
                            CountryName = "Latvia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 92,
                            CountryName = "Armenia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 93,
                            CountryName = "Montenegro",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 94,
                            CountryName = "Faroe Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 95,
                            CountryName = "Bahrain",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 96,
                            CountryName = "USA",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 97,
                            CountryName = "Canada",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 98,
                            CountryName = "France",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 99,
                            CountryName = "Spain",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 100,
                            CountryName = "Greece",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 101,
                            CountryName = "Morocco",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 102,
                            CountryName = "Egypt",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 103,
                            CountryName = "South Africa",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 104,
                            CountryName = "Italy",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 105,
                            CountryName = "Ghana",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 106,
                            CountryName = "Mauritius",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 107,
                            CountryName = "Kenya",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 108,
                            CountryName = "Angola",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 109,
                            CountryName = "Togo",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 110,
                            CountryName = "Jordan",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 111,
                            CountryName = "Zambia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 112,
                            CountryName = "Senegal",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 113,
                            CountryName = "Ethiopia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 114,
                            CountryName = "Cyprus",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 115,
                            CountryName = "Namibia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 116,
                            CountryName = "Gambia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 117,
                            CountryName = "Portugal",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 118,
                            CountryName = "Djibouti",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 119,
                            CountryName = "Mauritania",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 120,
                            CountryName = "Sudan",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 121,
                            CountryName = "Mozambique",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 122,
                            CountryName = "Algeria",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 123,
                            CountryName = "Tunisia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 124,
                            CountryName = "Tanzania",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 125,
                            CountryName = "Ivory Coast",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 126,
                            CountryName = "Guinea",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 127,
                            CountryName = "Uganda",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 128,
                            CountryName = "Nigeria",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 129,
                            CountryName = "Libya",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 130,
                            CountryName = "Cabo Verde",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 131,
                            CountryName = "Lesotho",
                            RegionId = 7
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.MileStone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("MileStoneName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mile_stone_name");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.HasKey("Id")
                        .HasName("pk_mile_stones");

                    b.ToTable("mile_stones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM020 - Bid decision"
                        },
                        new
                        {
                            Id = 2,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM040 - Binding offer"
                        },
                        new
                        {
                            Id = 3,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM070 - Contract signature"
                        },
                        new
                        {
                            Id = 4,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM080 - Notice to proceed"
                        },
                        new
                        {
                            Id = 5,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "Certification Target"
                        },
                        new
                        {
                            Id = 6,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM650 - Take-over to customer"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer")
                        .HasColumnName("permission_type");

                    b.Property<int>("ProjectModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("project_module_id");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("ProjectModuleId")
                        .HasDatabaseName("ix_permissions_project_module_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permissions_role_id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<string>("ContractStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_status");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("RecordEndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_end_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("SSTRequestSimilarProjects")
                        .HasColumnType("text")
                        .HasColumnName("sst_request_similar_projects");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_projects_country_id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectMileStones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("MileStoneDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mile_stone_date");

                    b.Property<int>("MileStoneId")
                        .HasColumnType("integer")
                        .HasColumnName("mile_stone_id");

                    b.Property<string>("MileStoneOfferStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mile_stone_offer_status");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_mile_stones");

                    b.HasIndex("MileStoneId")
                        .HasDatabaseName("ix_project_mile_stones_mile_stone_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_mile_stones_project_id");

                    b.ToTable("project_mile_stones");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("ModuleDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_description");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_name");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_project_modules");

                    b.ToTable("project_modules");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("userId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_roles_project_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_project_roles_role_id");

                    b.ToTable("project_roles");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<DateTime>("CertificationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("certification_date");

                    b.Property<int>("CertificationId")
                        .HasColumnType("integer")
                        .HasColumnName("certification_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("ProposalSfId")
                        .HasColumnType("text")
                        .HasColumnName("proposal_sf_id");

                    b.Property<DateTime?>("RecordEndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_end_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.HasKey("Id")
                        .HasName("pk_proposals");

                    b.HasIndex("CertificationId")
                        .HasDatabaseName("ix_proposals_certification_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_proposals_project_id");

                    b.ToTable("proposals");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProposalTasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_customer");

                    b.Property<int>("ProposalId")
                        .HasColumnType("integer")
                        .HasColumnName("proposal_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_proposal_tasks");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("ix_proposal_tasks_proposal_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_proposal_tasks_task_id");

                    b.ToTable("proposal_tasks");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Quotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("ProposalId")
                        .HasColumnType("integer")
                        .HasColumnName("proposal_id");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("SfOfferStatus")
                        .HasColumnType("text")
                        .HasColumnName("sf_offer_status");

                    b.Property<bool>("SfOfferType")
                        .HasColumnType("boolean")
                        .HasColumnName("sf_offer_type");

                    b.Property<string>("SfQuotationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sf_quotation_id");

                    b.Property<string>("SfQuotationName")
                        .HasColumnType("text")
                        .HasColumnName("sf_quotation_name");

                    b.Property<bool>("SfQuotationStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("sf_quotation_status");

                    b.Property<DateTime>("SfQuoteSubmissionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sf_quote_submission_date");

                    b.Property<string>("SfSarCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sf_sar_code");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("ix_quotes_proposal_id");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region_name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionName = "APAC"
                        },
                        new
                        {
                            Id = 2,
                            RegionName = "BRAZIL"
                        },
                        new
                        {
                            Id = 3,
                            RegionName = "INDIA"
                        },
                        new
                        {
                            Id = 4,
                            RegionName = "LATAM"
                        },
                        new
                        {
                            Id = 5,
                            RegionName = "NE&ME"
                        },
                        new
                        {
                            Id = 6,
                            RegionName = "NORTH AMERICA"
                        },
                        new
                        {
                            Id = 7,
                            RegionName = "SE&A"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_name");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Opportunity Owner / Sales Manger",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Proposal Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Siting Engineer",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Technical Project Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Global Project Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Planning Towers",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Procurement Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Logistic Pre-Sales Road Engineer",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "PR Pre-Sales (Logistic)",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "PR Pre-Sales (Construction)",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Construction Technical Office",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Tower Development",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Loads and Control Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Certification Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.SarStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdateDTM")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update_dtm");

                    b.Property<DateTime>("RecordInsertDTM")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_dtm");

                    b.HasKey("Id")
                        .HasName("pk_sar_studies");

                    b.ToTable("sar_studies");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("TaskName")
                        .HasColumnType("text")
                        .HasColumnName("task_name");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TaskName = "Tower design"
                        },
                        new
                        {
                            Id = 2,
                            TaskName = "Foundation design"
                        },
                        new
                        {
                            Id = 3,
                            TaskName = "Anchor Cage design"
                        },
                        new
                        {
                            Id = 4,
                            TaskName = "Preliminary Logistic Assessment"
                        },
                        new
                        {
                            Id = 5,
                            TaskName = "Road Survey"
                        },
                        new
                        {
                            Id = 6,
                            TaskName = "Transport oversea"
                        },
                        new
                        {
                            Id = 7,
                            TaskName = "Transport inland"
                        },
                        new
                        {
                            Id = 8,
                            TaskName = "Anchor cage delivery"
                        },
                        new
                        {
                            Id = 9,
                            TaskName = "Foundation construction"
                        },
                        new
                        {
                            Id = 10,
                            TaskName = "Tower installation"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.WtgCatalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<float>("WtgSizeMW")
                        .HasColumnType("real")
                        .HasColumnName("wtg_size_mw");

                    b.Property<string>("WtgType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("wtg_type");

                    b.HasKey("Id")
                        .HasName("pk_wtg_catalogues");

                    b.ToTable("wtg_catalogues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WtgSizeMW = 6f,
                            WtgType = "SG 6.0-170"
                        },
                        new
                        {
                            Id = 2,
                            WtgSizeMW = 6f,
                            WtgType = "SG 6.0-155"
                        },
                        new
                        {
                            Id = 3,
                            WtgSizeMW = 5f,
                            WtgType = "SG 5.0-145"
                        },
                        new
                        {
                            Id = 4,
                            WtgSizeMW = 5f,
                            WtgType = "SG 5.0-132"
                        },
                        new
                        {
                            Id = 5,
                            WtgSizeMW = 4f,
                            WtgType = "SG 4.5-145"
                        },
                        new
                        {
                            Id = 6,
                            WtgSizeMW = 4f,
                            WtgType = "SG 4.5-132"
                        },
                        new
                        {
                            Id = 7,
                            WtgSizeMW = 3.465f,
                            WtgType = "SG 3.4-132 CIIA"
                        },
                        new
                        {
                            Id = 8,
                            WtgSizeMW = 3.465f,
                            WtgType = "SG 3.4-132 CIA"
                        },
                        new
                        {
                            Id = 9,
                            WtgSizeMW = 3.465f,
                            WtgType = "SG 3.4-145 CS"
                        },
                        new
                        {
                            Id = 10,
                            WtgSizeMW = 2.625f,
                            WtgType = "SG 2.6-114 CIA"
                        },
                        new
                        {
                            Id = 11,
                            WtgSizeMW = 2.625f,
                            WtgType = "SG 2.6-114 CIIA MY18"
                        },
                        new
                        {
                            Id = 12,
                            WtgSizeMW = 2.625f,
                            WtgType = "SG 2.6-114 CS MY20"
                        },
                        new
                        {
                            Id = 13,
                            WtgSizeMW = 2.14f,
                            WtgType = "SG 2.1-114 CIIA/IIIA MY18"
                        },
                        new
                        {
                            Id = 14,
                            WtgSizeMW = 2.2f,
                            WtgType = "SG 2.2-122"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.WtgConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("QuantityTrigger")
                        .HasColumnType("boolean")
                        .HasColumnName("quantity_trigger");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<int>("WindfarmSize")
                        .HasColumnType("integer")
                        .HasColumnName("windfarm_size");

                    b.Property<bool>("WindfarmSizeTrigger")
                        .HasColumnType("boolean")
                        .HasColumnName("windfarm_size_trigger");

                    b.Property<int>("WtgCatalogueId")
                        .HasColumnType("integer")
                        .HasColumnName("wtg_catalogue_id");

                    b.HasKey("Id")
                        .HasName("pk_wtg_configurations");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_wtg_configurations_quote_id");

                    b.HasIndex("WtgCatalogueId")
                        .HasDatabaseName("ix_wtg_configurations_wtg_catalogue_id");

                    b.ToTable("wtg_configurations");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Country", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_countries_regions_region_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Permission", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.ProjectModule", "ProjectModule")
                        .WithMany()
                        .HasForeignKey("ProjectModuleId")
                        .HasConstraintName("fk_permissions_project_modules_project_module_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permissions_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectModule");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_projects_countries_country_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectMileStones", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.MileStone", "MileStone")
                        .WithMany()
                        .HasForeignKey("MileStoneId")
                        .HasConstraintName("fk_project_mile_stones_mile_stones_mile_stone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany("ProjectMileStones")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_mile_stones_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MileStone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectRoles", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_roles_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_project_roles_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .HasConstraintName("fk_proposals_certifications_certification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany("Proposals")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_proposals_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProposalTasks", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Proposal", "Proposal")
                        .WithMany("ProposalTasks")
                        .HasForeignKey("ProposalId")
                        .HasConstraintName("fk_proposal_tasks_proposals_proposal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .HasConstraintName("fk_proposal_tasks_tasks_task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Quotes", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Proposal", "Proposal")
                        .WithMany("Quotes")
                        .HasForeignKey("ProposalId")
                        .HasConstraintName("fk_quotes_proposals_proposal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.WtgConfiguration", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Quotes", "Quote")
                        .WithMany("WtgConfiguations")
                        .HasForeignKey("QuoteId")
                        .HasConstraintName("fk_wtg_configurations_quotes_quote_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.WtgCatalogue", "WtgCatalogue")
                        .WithMany()
                        .HasForeignKey("WtgCatalogueId")
                        .HasConstraintName("fk_wtg_configurations_wtg_catalogues_wtg_catalogue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("WtgCatalogue");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.Navigation("ProjectMileStones");

                    b.Navigation("ProjectRoles");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.Navigation("ProposalTasks");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Quotes", b =>
                {
                    b.Navigation("WtgConfiguations");
                });
#pragma warning restore 612, 618
        }
    }
}
