// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGRE.TSA.DataStore.API;

namespace SGRE.TSA.DataStore.API.Migrations
{
    [DbContext(typeof(TsaContext))]
    [Migration("20201203091808_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country_name");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_countries_region_id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.MileStone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("MileStoneName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mile_stone_name");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.HasKey("Id")
                        .HasName("pk_mile_stones");

                    b.ToTable("mile_stones");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer")
                        .HasColumnName("permission_type");

                    b.Property<int>("ProjectModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("project_module_id");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("ProjectModuleId")
                        .HasDatabaseName("ix_permissions_project_module_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permissions_role_id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<string>("ContractStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_status");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("RecordEndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_end_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("SSTRequestSimilarProjects")
                        .HasColumnType("text")
                        .HasColumnName("sst_request_similar_projects");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_projects_country_id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectMileStones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("MileStoneDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mile_stone_date");

                    b.Property<int>("MileStoneId")
                        .HasColumnType("integer")
                        .HasColumnName("mile_stone_id");

                    b.Property<string>("MileStoneOfferStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mile_stone_offer_status");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_mile_stones");

                    b.HasIndex("MileStoneId")
                        .HasDatabaseName("ix_project_mile_stones_mile_stone_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_mile_stones_project_id");

                    b.ToTable("project_mile_stones");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("ModuleDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_description");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_name");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_project_modules");

                    b.ToTable("project_modules");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("userId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_roles_project_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_project_roles_role_id");

                    b.ToTable("project_roles");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("ProposalId")
                        .HasColumnType("text")
                        .HasColumnName("proposal_id");

                    b.Property<string>("ProposalStatus")
                        .HasColumnType("text")
                        .HasColumnName("proposal_status");

                    b.Property<DateTime?>("RecordEndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_end_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.HasKey("Id")
                        .HasName("pk_proposals");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_proposals_project_id");

                    b.ToTable("proposals");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region_name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("active_record_indicator");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_name");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Sales Manger",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 2,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Proposal Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 3,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Siting Engineer",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 4,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Technical Project Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 5,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Global Project Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 6,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Planning Towers",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 7,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Procurement Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 8,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Logistic Pre-Sales Road Engineer",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 9,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "PR Pre-Sales (Logistic)",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 10,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "PR Pre-Sales (Construction)",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 11,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Construction Technical Office",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 12,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Tower Development",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 13,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Loads and Control Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 14,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordInsertDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Certification Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Country", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_countries_regions_region_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Permission", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.ProjectModule", "ProjectModule")
                        .WithMany()
                        .HasForeignKey("ProjectModuleId")
                        .HasConstraintName("fk_permissions_project_modules_project_module_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permissions_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectModule");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_projects_countries_country_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectMileStones", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.MileStone", "MileStone")
                        .WithMany()
                        .HasForeignKey("MileStoneId")
                        .HasConstraintName("fk_project_mile_stones_mile_stones_mile_stone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_mile_stones_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MileStone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectRoles", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_roles_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_project_roles_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany("Proposals")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_proposals_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
