// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGRE.TSA.DataStore.API;

namespace SGRE.TSA.DataStore.API.Migrations
{
    [DbContext(typeof(TsaContext))]
    [Migration("20201203112840_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country_name");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_countries_region_id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "China",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Japan",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "South Korea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Australia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "Vietnam",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "New Zealand",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Philippines",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Indonesia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Taiwan",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Pakistan",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Mongolia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Thailand",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Myanmar",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "New Caledonia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Cambodia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Laos",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Brazil",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "India",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Sri Lanka",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Bangladesh",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Brazil",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Mexico",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Peru",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Dominican Rep.",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "Argentina",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Panama",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Chile",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Uruguay",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Colombia",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 30,
                            CountryName = "Belize",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 31,
                            CountryName = "Nicaragua",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 32,
                            CountryName = "Jamaica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 33,
                            CountryName = "Guatemala",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 34,
                            CountryName = "Honduras",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 35,
                            CountryName = "Costa Rica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 36,
                            CountryName = "El Salvador",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 37,
                            CountryName = "Cuba",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 38,
                            CountryName = "Dominica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 39,
                            CountryName = "Guyana",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 40,
                            CountryName = "Ecuador",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 41,
                            CountryName = "Guadeloupe",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 42,
                            CountryName = "Puerto Rico",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 43,
                            CountryName = "Trinidad Tobago",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 44,
                            CountryName = "Bahamas",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 45,
                            CountryName = "Bolivia",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 46,
                            CountryName = "Barbados",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 47,
                            CountryName = "Ireland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 48,
                            CountryName = "Sweden",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 49,
                            CountryName = "Germany",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 50,
                            CountryName = "Romania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 51,
                            CountryName = "Croatia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 52,
                            CountryName = "Finland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 53,
                            CountryName = "Belgium",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 54,
                            CountryName = "Uzbekistan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 55,
                            CountryName = "Serbia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 56,
                            CountryName = "United Kingdom",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 57,
                            CountryName = "Poland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 58,
                            CountryName = "Saudi Arabia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 59,
                            CountryName = "Denmark",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 60,
                            CountryName = "Utd Arab Emir.",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 61,
                            CountryName = "Ukraine",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 62,
                            CountryName = "Bulgaria",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 63,
                            CountryName = "Azerbaijan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 64,
                            CountryName = "Turkey",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 65,
                            CountryName = "Norway",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 66,
                            CountryName = "Moldovia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 67,
                            CountryName = "Iran Islamic Republic of",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 68,
                            CountryName = "Russian Fed.",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 69,
                            CountryName = "Bosnia-Herz.",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 70,
                            CountryName = "Israel",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 71,
                            CountryName = "Lebanon",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 72,
                            CountryName = "Kazakhstan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 73,
                            CountryName = "Slovenia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 74,
                            CountryName = "Netherlands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 75,
                            CountryName = "Hungary",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 76,
                            CountryName = "Albania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 77,
                            CountryName = "Austria",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 78,
                            CountryName = "Oman",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 79,
                            CountryName = "Switzerland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 80,
                            CountryName = "Georgia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 81,
                            CountryName = "Syrian Arab Republic",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 82,
                            CountryName = "Macedonia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 83,
                            CountryName = "Luxembourg",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 84,
                            CountryName = "Kuwait",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 85,
                            CountryName = "Czech Republic",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 86,
                            CountryName = "Yemen",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 87,
                            CountryName = "Belarus",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 88,
                            CountryName = "Lithuania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 89,
                            CountryName = "Iceland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 90,
                            CountryName = "Estonia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 91,
                            CountryName = "Latvia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 92,
                            CountryName = "Armenia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 93,
                            CountryName = "Montenegro",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 94,
                            CountryName = "Faroe Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 95,
                            CountryName = "Bahrain",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 96,
                            CountryName = "USA",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 97,
                            CountryName = "Canada",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 98,
                            CountryName = "France",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 99,
                            CountryName = "Spain",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 100,
                            CountryName = "Greece",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 101,
                            CountryName = "Morocco",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 102,
                            CountryName = "Egypt",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 103,
                            CountryName = "South Africa",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 104,
                            CountryName = "Italy",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 105,
                            CountryName = "Ghana",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 106,
                            CountryName = "Mauritius",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 107,
                            CountryName = "Kenya",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 108,
                            CountryName = "Angola",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 109,
                            CountryName = "Togo",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 110,
                            CountryName = "Jordan",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 111,
                            CountryName = "Zambia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 112,
                            CountryName = "Senegal",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 113,
                            CountryName = "Ethiopia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 114,
                            CountryName = "Cyprus",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 115,
                            CountryName = "Namibia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 116,
                            CountryName = "Gambia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 117,
                            CountryName = "Portugal",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 118,
                            CountryName = "Djibouti",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 119,
                            CountryName = "Mauritania",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 120,
                            CountryName = "Sudan",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 121,
                            CountryName = "Mozambique",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 122,
                            CountryName = "Algeria",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 123,
                            CountryName = "Tunisia",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 124,
                            CountryName = "Tanzania",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 125,
                            CountryName = "Ivory Coast",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 126,
                            CountryName = "Guinea",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 127,
                            CountryName = "Uganda",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 128,
                            CountryName = "Nigeria",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 129,
                            CountryName = "Libya",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 130,
                            CountryName = "Cabo Verde",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 131,
                            CountryName = "Lesotho",
                            RegionId = 7
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.MileStone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("MileStoneName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mile_stone_name");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.HasKey("Id")
                        .HasName("pk_mile_stones");

                    b.ToTable("mile_stones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM020 - Bid decision"
                        },
                        new
                        {
                            Id = 2,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM070 - Contract signature"
                        },
                        new
                        {
                            Id = 3,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM080 - Notice to proceed"
                        },
                        new
                        {
                            Id = 4,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "Certification Target"
                        },
                        new
                        {
                            Id = 5,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MileStoneName = "PM650 - Take-over to customer"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer")
                        .HasColumnName("permission_type");

                    b.Property<int>("ProjectModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("project_module_id");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("ProjectModuleId")
                        .HasDatabaseName("ix_permissions_project_module_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permissions_role_id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<string>("ContractStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_status");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("RecordEndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_end_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("SSTRequestSimilarProjects")
                        .HasColumnType("text")
                        .HasColumnName("sst_request_similar_projects");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_projects_country_id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectMileStones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("MileStoneDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mile_stone_date");

                    b.Property<int>("MileStoneId")
                        .HasColumnType("integer")
                        .HasColumnName("mile_stone_id");

                    b.Property<string>("MileStoneOfferStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mile_stone_offer_status");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_mile_stones");

                    b.HasIndex("MileStoneId")
                        .HasDatabaseName("ix_project_mile_stones_mile_stone_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_mile_stones_project_id");

                    b.ToTable("project_mile_stones");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<string>("ModuleDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_description");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_name");

                    b.Property<DateTime>("RecordInsertDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_project_modules");

                    b.ToTable("project_modules");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("userId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_roles_project_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_project_roles_role_id");

                    b.ToTable("project_roles");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("active_record_indicator");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("ProposalId")
                        .HasColumnType("text")
                        .HasColumnName("proposal_id");

                    b.Property<string>("ProposalStatus")
                        .HasColumnType("text")
                        .HasColumnName("proposal_status");

                    b.Property<DateTime?>("RecordEndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_end_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.HasKey("Id")
                        .HasName("pk_proposals");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_proposals_project_id");

                    b.ToTable("proposals");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region_name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionName = "APAC"
                        },
                        new
                        {
                            Id = 2,
                            RegionName = "BRAZIL"
                        },
                        new
                        {
                            Id = 3,
                            RegionName = "INDIA"
                        },
                        new
                        {
                            Id = 4,
                            RegionName = "LATAM"
                        },
                        new
                        {
                            Id = 5,
                            RegionName = "NE&ME"
                        },
                        new
                        {
                            Id = 6,
                            RegionName = "NORTH AMERICA"
                        },
                        new
                        {
                            Id = 7,
                            RegionName = "SE&A"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ActiveRecordIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("active_record_indicator");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<DateTime?>("RecordInsertDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("record_insert_date_time");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_name");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Opportunity Owner / Sales Manger",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 2,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Proposal Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 3,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Siting Engineer",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 4,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Technical Project Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 5,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Global Project Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 6,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Planning Towers",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 7,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Procurement Manager",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 8,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Logistic Pre-Sales Road Engineer",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 9,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "PR Pre-Sales (Logistic)",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 10,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "PR Pre-Sales (Construction)",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 11,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Construction Technical Office",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 12,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Tower Development",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 13,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Loads and Control Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        },
                        new
                        {
                            Id = 14,
                            ActiveRecordIndicator = 0,
                            CreatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com",
                            RoleName = "Certification Engineering",
                            UpdatedBy = "visweswara.dontamsetti.ext@siemensgamesa.com"
                        });
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Country", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_countries_regions_region_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Permission", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.ProjectModule", "ProjectModule")
                        .WithMany()
                        .HasForeignKey("ProjectModuleId")
                        .HasConstraintName("fk_permissions_project_modules_project_module_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permissions_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectModule");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_projects_countries_country_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectMileStones", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.MileStone", "MileStone")
                        .WithMany()
                        .HasForeignKey("MileStoneId")
                        .HasConstraintName("fk_project_mile_stones_mile_stones_mile_stone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_mile_stones_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MileStone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.ProjectRoles", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_roles_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGRE.TSA.DataStore.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_project_roles_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Proposal", b =>
                {
                    b.HasOne("SGRE.TSA.DataStore.API.Models.Project", "Project")
                        .WithMany("Proposals")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_proposals_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SGRE.TSA.DataStore.API.Models.Project", b =>
                {
                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
